server:
  port: 8090
spring:
  profiles.active: prod
---
spring:
  profiles: robot
  jpa:
    hibernate:
      ddl-auto: validate
    database: MYSQL
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_second_level_cache: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/robot?useSSL=false
    username: root
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
---
spring:
  profiles: prod
spring.profiles.include: robot